# Generated by Django 4.1 on 2023-12-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_data_date', models.DateTimeField(verbose_name='date of the prices')),
                ('asset_close_price', models.FloatField()),
                ('asset_open_price', models.FloatField()),
                ('asset_high_price', models.FloatField()),
                ('asset_low_price', models.FloatField()),
                ('asset_volume', models.BigIntegerField()),
            ],
        ),
    ]
