# Generated by Django 4.1 on 2023-12-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiinvest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetdata',
            old_name='asset_id',
            new_name='asset',
        ),
    ]
