

create database ai1;
revoke all on database ai1 from public;


create role aiwrite;
GRANT connect on database ai1 to aiwrite;

GRANT USAGE, CREATE ON SCHEMA PUBLIC TO AIWRITE;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PUBLIC TO AIWRITE;
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO AIWRITE;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA PUBLIC TO AIWRITE;
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC GRANT USAGE ON SEQUENCES TO AIWRITE;

create user aiapp with password '080802';

grant aiwrite to aiapp;

CREATE ROLE airead;
GRANT connect on database ai1 to airead;
GRANT USAGE ON SCHEMA PUBLIC TO airead;
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO airead;
ALTER DEFAULT PRIVILEGES in SCHEMA PUBLIC GRANT SELECT ON TABLES TO airead;